name: 02 - Test Action

on:
  workflow_dispatch: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

run-name: Test Action - ${{ github.event_name }}

jobs:
  test-my-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '>=22.5.1' # Changed to match action.yml node20 runtime

      - name: Install dependencies
        run: npm ci --verbose

      # Test with custom input
      - name: Test Custom Input
        uses: ./
        id: action-test
        with:
          user-name: 'Renan Almeida'

      - name: Ensure custom greeting is correct
        if: steps.action-test.outputs.greeting == 'Hello Renan Almeida!'
        run: |
          echo "Greeting matches expected value: ${{ steps.action-test.outputs.greeting }}"

      - name: Output if custom greeting does not match
        if: steps.action-test.outputs.greeting != 'Hello Renan Almeida!'
        run: |
          echo "Greeting does not match expected value."
          echo "Expected: Hello Renan Almeida!"
          echo "Actual: ${{ steps.action-test.outputs.greeting }}"
          exit 1

      # Test with default input
      - name: Test Default Input
        uses: ./
        id: default-test

      - name: Verify Default Greeting
        if: steps.default-test.outputs.greeting == 'Hello Renan!'
        run: |
          echo "Default greeting works: ${{ steps.default-test.outputs.greeting }}"

      - name: Output if default greeting does not match
        if: steps.default-test.outputs.greeting != 'Hello Renan!'
        run: |
          echo "Default greeting does not match expected value."
          echo "Expected: Hello Renan!"
          echo "Actual: ${{ steps.default-test.outputs.greeting }}"
          exit 1

      # Test outputs
      - name: Verify time output
        run: |
          if [[ -z "${{ steps.action-test.outputs.time }}" ]]; then
            echo "Time output is missing"
            exit 1
          else
            echo "The time was ${{ steps.action-test.outputs.time }}"
          fi
